language: go
install:
    - go get gopkg.in/labstack/echo.v1
go:
    # - "1.0" # unsupported by echo
    # - "1.1"
    # - "1.2"
    - "1.3"
    - "1.4"
    - "1.5"
    - "1.6"
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - "tip"
