version: 2

defaults: &defaults
  working_directory: /go/src/gopkg.in/nowk/ripple.v1
  docker:
    - image: golang:1.10

jobs:
  build:
    <<: *defaults
    steps:
      - run: go get -u gopkg.in/nowk/ripple.v1
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test -v ./...

