version: 2

defaults: &defaults
  working_directory: /go/src/github.com/nowk/ripple
  docker:
    - image: golang:1.10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test -v ./..

